import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import * as Sentry from '@sentry/react'
import './assets/index.css'
import App from './App'
import { ErrorBoundary } from './shared/components/ErrorBoundary'
import { reportError } from './shared/services/errors/reportError'
import { initI18n } from './lang/index'

// --- GLOBAL FORENSIC MONITORING ---
console.info('[Forensic] Frontend entry point loading...')

// Fix memory leak: Clear performance marks/measures generated by 3rd party libs (like Sentry/React)
setInterval(() => {
  if (typeof performance !== 'undefined' && performance.clearMeasures && performance.clearMarks) {
    performance.clearMeasures()
    performance.clearMarks()
  }
}, 10000)

const sentryDsn =
  (import.meta.env.VITE_SENTRY_DSN || '').trim() ||
  'https://0f390845548c80602b5a61531b1c63de@o4511053995769856.ingest.us.sentry.io/4511054084505600'

Sentry.init({
  dsn: sentryDsn,
  sendDefaultPii: true,
})

globalThis.onerror = function(message, source, lineno, colno, error) {
  reportError('frontend', 'globalThis.onerror', error || message, {
    message,
    source,
    lineno,
    colno,
  })
  return false
}

globalThis.onunhandledrejection = function(event) {
  reportError('frontend', 'unhandledrejection', event.reason)
}

console.info('[Forensic] Global error handlers hooked.')

const boot = async () => {
  let initialLng
  try {
    initialLng = localStorage.getItem('gd-language') || undefined
  } catch {
    initialLng = undefined
  }

  try {
    await initI18n(initialLng)
  } catch (err) {
    console.error('[i18n] init failed:', err)
  }

  createRoot(document.getElementById('root')).render(
    <StrictMode>
      <ErrorBoundary>
        <App />
      </ErrorBoundary>
    </StrictMode>
  )
}

boot()
