import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { LazyMotion, domMax } from 'framer-motion'
import './assets/index.css'
import App from './App'
import { ErrorBoundary } from './shared/components/ErrorBoundary'
import { reportError } from './shared/services/errors/reportError'
import { initI18n } from './lang/index'

// --- GLOBAL FORENSIC MONITORING ---
console.info('[Forensic] Frontend entry point loading...')

// Fix memory leak: Clear performance marks/measures generated by 3rd party libs
setInterval(() => {
  if (typeof performance !== 'undefined' && performance.clearMeasures && performance.clearMarks) {
    performance.clearMeasures()
    performance.clearMarks()
  }
}, 10000)

globalThis.onerror = function(message, source, lineno, colno, error) {
  reportError('frontend', 'globalThis.onerror', error || message, {
    message,
    source,
    lineno,
    colno,
  })
  return false
}

globalThis.onunhandledrejection = function(event) {
  reportError('frontend', 'unhandledrejection', event.reason)
}

console.info('[Forensic] Global error handlers hooked.')

// React Scan (dev-only render inspector). Dynamic import keeps it out of the
// production bundle; the DEV gate keeps it out of Tauri release builds.
if (import.meta.env.DEV) {
  void import('react-scan').then(({ scan }) => {
    scan({ enabled: true, showToolbar: true, animationSpeed: 'fast' });
  }).catch(() => {
    // Never break boot if the inspector fails to load.
  });
}

const boot = async () => {
  let initialLng
  try {
    initialLng = localStorage.getItem('gd-language') || undefined
  } catch {
    initialLng = undefined
  }

  try {
    await initI18n(initialLng)
  } catch (err) {
    console.error('[i18n] init failed:', err)
  }

  createRoot(document.getElementById('root')).render(
    <StrictMode>
      <LazyMotion features={domMax}>
        <ErrorBoundary>
          <App />
        </ErrorBoundary>
      </LazyMotion>
    </StrictMode>
  )
}

boot()
